# Generated by Django 4.2 on 2024-03-05 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_remove_profile_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
