# Generated by Django 4.2 on 2024-03-04 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='feature',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='slug',
            field=models.SlugField(null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
