# Generated by Django 4.2 on 2024-03-05 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0004_alter_category_slug_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='Project',
            new_name='project',
        ),
    ]
