# Generated by Django 4.2 on 2024-03-06 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0004_alter_category_slug_donate'),
        ('campaign', '0005_rename_project_review_project'),
    ]

    operations = [
    ]
