# Generated by Django 4.2 on 2024-03-06 09:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0006_merge_20240306_1055'),
    ]

    operations = [
        migrations.AddField(
            model_name='donate',
            name='donated_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
